### ISSUE TITLE
ModuleNotFoundError: No module named 'phish.loss', potential file missing?

### ISSUE THREAD

**Issue by Vincentzyx** [tpanum/towards-adversarial-phishing-detection#1]
Hi, I'm currently trying to run your code, running into the error below, I wonder if there's any code that you forget to push to this repo? Thank you!
```
python.exe train.py 
Traceback (most recent call last):
  File "\towards-adversarial-phishing-detection-master\train.py", line 15, in <module>
    from phish.whitenet import WhiteNetModel
  File "\towards-adversarial-phishing-detection-master\phish\whitenet.py", line 8, in <module>
    from .loss import _get_predictions
ModuleNotFoundError: No module named 'phish.loss'
```

**Comment by tpanum** [comment]
Thanks. You're right. Unfortunately, it's a while since I did this research and I don't work in academia anymore. I have however, tried to dig out the missing file, and I believe (or hope) I found the correct file and created a merge request [here](https://github.com/tpanum/towards-adversarial-phishing-detection/pull/2). If it works, feel free to let me know, then I'll merge it into master.
